dist: trusty
sudo: required

language: python
python:
  - "2.7"
  - "3.5"
#TODO:  - "pypy"

install:
  # VineCopula requires copula R package which requires R>3.1 which requires Ubuntu > trusty (but trusty failed, so using yakkety)
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ yakkety main universe"
  - sudo apt-get update

  - sudo apt-get install --no-install-recommends -t yakkety -y libgsl0-dev r-base-dev g++
  - sudo apt-get autoremove # in particular remove old compilers so that new ones are the default
  - sudo Rscript -e 'withCallingHandlers(install.packages("VineCopula", repos="http://cran.rstudio.com"), warning=function(x) { message(x); quit(status=1, save="no") })'
  - pip install cffi

script: python -m pytest

notifications:
  slack: chatham:CcaaNGXV2IUiKvPqH1m6UHZa