language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install numpy
  - pip install cffi
  - pip install pytest

script:
  - python -m pytest

notifications:
  slack: chatham:CcaaNGXV2IUiKvPqH1m6UHZa